### PR TITLE
Naming improvements for linters

### PR DESCRIPTION
**Pull request by manuelpuyol**
Renames `Helpers` to `BaseLinter` and updates `classes_to_args` to receive a list of classes instead of a string

### CODE REVIEW

**Review by camertron — CHANGES_REQUESTED** [review]
Hmm, I'm not sure `BaseLinter` communicates what this module does. The comment above it says "Helper methods for linting ERB." Have you considered `ERBLintingHelpers` or maybe `ERBLinting`? In my experience it's more common to see _classes_ named `Base*` and for them to be inherited directly instead of mixed-in.

**Comment by manuelpuyol** [comment]
> Hmm, I'm not sure `BaseLinter` communicates what this module does. The comment above it says "Helper methods for linting ERB." Have you considered `ERBLintingHelpers` or maybe `ERBLinting`? In my experience it's more common to see _classes_ named `Base*` and for them to be inherited directly instead of mixed-in. 😄 😄

hmm maybe the comment should be updated, that module actually holds **all** the linter logic, the classes that include it only have to set some configuration variables
I agree it _should_ be a class, but I had to make it a module because of some `erb_lint` quirks (custom linters have to inherit from `ERBLint::Linters::Base`) so the only way of sharing the logic was through a module :/

going to update the module docs to reflect that change :)

**Comment by camertron** [comment]
@manuelpuyol ah ok that's good to know! Not to completely change the architecture of our linters, but what if `BaseLinter` inherited from `ERBLint::Linters::Base` and each individual linter then inherited from `BaseLinter`?

**Comment by manuelpuyol** [comment]
> @manuelpuyol ah ok that's good to know! Not to completely change the architecture of our linters, but what if `BaseLinter` inherited from `ERBLint::Linters::Base` and each individual linter then inherited from `BaseLinter`?

I've tried that in the past but it didn't work 😢

**Comment by camertron** [comment]
@manuelpuyol shoot 😞  What went wrong?

**Comment by manuelpuyol** [comment]
> @manuelpuyol shoot 😞 What went wrong?

I'll give it a try again, I remember that some configs weren't being applied when subclassing like that
But `erb_lint` received some good updates since then, maybe I can figure it out this time!

**Comment by manuelpuyol** [comment]
@camertron I've updated the PR using inheritance 🎉

**Review by camertron — APPROVED** [review]
🎉 🎉 🎉

**Pull request merged**
