### PR TITLE
Promote Base and BlankSlate components to beta

### PR DESCRIPTION
**Pull request by srt32**

### CODE REVIEW

**Comment by manuelpuyol** [comment]
I wonder id we want to expose `BaseComponent` to the outside world

**Comment by srt32** [comment]
It gets used in dotcom to make internal components so I think we need it at least for that purpose. What did you have in mind?

**Comment by manuelpuyol** [comment]
hmm I didn't expect it to be used

**Comment by srt32** [comment]
Still okay to promote it?

**Review by joelhawksley — APPROVED** [review]
👍🏻 to move this component to `beta`. We can (and should) ensure our documentation guides folks towards correct usages of this component.

**Pull request merged**
