### PR TITLE
Replace YAML load with YAML safe load with allowed classes list

### PR DESCRIPTION
**Pull request by HParker**
In Psych 4+ YAML.load will default to YAML.safe_load. it is worth using it here since it works with a small list of specified classes even though it is a static list that we supply ourselves

### CODE REVIEW

**Comment by jonrohan** [comment]
One issue I think I ran into with safe_load is it didn't preserve the types. eg. Some of the arguments are `:symbol, string, or integer` like `mr: :auto` or `mr: 1`. I thought converting them after loading the yml might be too slow?

**Comment by HParker** [comment]
It seems to do what I expect:

```
UTILITIES[:mr]
=> 
{0=>["mr-0", "mr-sm-0", "mr-md-0", "mr-lg-0", "mr-xl-0"],
 1=>["mr-1", "mr-sm-1", "mr-md-1", "mr-lg-1", "mr-xl-1"],
 -1=>["mr-n1", "mr-sm-n1", "mr-md-n1", "mr-lg-n1", "mr-xl-n1"],
 2=>["mr-2", "mr-sm-2", "mr-md-2", "mr-lg-2", "mr-xl-2"],
 -2=>["mr-n2", "mr-sm-n2", "mr-md-n2", "mr-lg-n2", "mr-xl-n2"],
 3=>["mr-3", "mr-sm-3", "mr-md-3", "mr-lg-3", "mr-xl-3"],
 -3=>["mr-n3", "mr-sm-n3", "mr-md-n3", "mr-lg-n3", "mr-xl-n3"],
 4=>["mr-4", "mr-sm-4", "mr-md-4", "mr-lg-4", "mr-xl-4"],
 -4=>["mr-n4", "mr-sm-n4", "mr-md-n4", "mr-lg-n4", "mr-xl-n4"],
 5=>["mr-5", "mr-sm-5", "mr-md-5", "mr-lg-5", "mr-xl-5"],
 -5=>["mr-n5", "mr-sm-n5", "mr-md-n5", "mr-lg-n5", "mr-xl-n5"],
 6=>["mr-6", "mr-sm-6", "mr-md-6", "mr-lg-6", "mr-xl-6"],
 -6=>["mr-n6", "mr-sm-n6", "mr-md-n6", "mr-lg-n6", "mr-xl-n6"],
 :auto=>["mr-auto"]}
```

```
UTILITIES[:col]
=> 
{1=>["col-1", "col-sm-1", "col-md-1", "col-lg-1", "col-xl-1"],
 2=>["col-2", "col-sm-2", "col-md-2", "col-lg-2", "col-xl-2"],
 3=>["col-3", "col-sm-3", "col-md-3", "col-lg-3", "col-xl-3"],
 4=>["col-4", "col-sm-4", "col-md-4", "col-lg-4", "col-xl-4"],
 5=>["col-5", "col-sm-5", "col-md-5", "col-lg-5", "col-xl-5"],
 6=>["col-6", "col-sm-6", "col-md-6", "col-lg-6", "col-xl-6"],
 7=>["col-7", "col-sm-7", "col-md-7", "col-lg-7", "col-xl-7"],
 8=>["col-8", "col-sm-8", "col-md-8", "col-lg-8", "col-xl-8"],
 9=>["col-9", "col-sm-9", "col-md-9", "col-lg-9", "col-xl-9"],
 10=>["col-10", "col-sm-10", "col-md-10", "col-lg-10", "col-xl-10"],
 11=>["col-11", "col-sm-11", "col-md-11", "col-lg-11", "col-xl-11"],
 12=>["col-12", "col-sm-12", "col-md-12", "col-lg-12", "col-xl-12"]}
```

**Comment by camertron** [comment]
It looks like that's because [`Psych.safe_load`](https://ruby-doc.org/stdlib-3.1.0/libdoc/psych/rdoc/Psych.html#method-c-safe_load) whitelists a number of types by default, including `TrueClass`, `FalseClass`, `NilClass`, `Integer`, `Float`, `String`, `Array`, and `Hash`.

**Comment by camertron** [comment]
I needed to add a changeset so I made another brach and opened a duplicate PR: https://github.com/primer/view_components/pull/1258

**Pull request closed without merging**
