### PR TITLE
Add `CtaLink` as Alpha component

### PR DESCRIPTION
**Pull request by pouretrebelle**
This introduces an experimental component to explore visually separating links from buttons, as discussed in 
https://github.com/github/primer/discussions/477 and highlighted in [Button a11y audit](https://github.com/github/primer/issues/366) and [API audit](https://github.com/github/primer/issues/253#issuecomment-956563038).

It has the same API as Button apart from removing the `link` scheme and button-related args.

## [Preview](https://view-components-nb78xjx46-primer.vercel.app/view-components/components/alpha/ctalink)

Screenshot 2021-12-16 at 19 25 05
Screenshot 2021-12-16 at 19 25 28

### CODE REVIEW

**Comment by pouretrebelle** [comment]
@manuelpuyol I'm not sure what's up with these tests, could you take a look?

**Review by jonrohan — APPROVED** [review]
This looks great 🎉

**Comment by pouretrebelle** [comment]
`ArgumentError: Primer::ButtonComponent declares the leading_visual slot multiple times.` - I'm assuming this is because we're extending ButtonComponent in CtaLink? This error didn't occur with the last button changes in #924 🤔 I don't know enough about Rails to debug/solve this on my own 😞

**Comment by lesliecdubs** [comment]
Hey @jonrohan, I recognize this is a blast from the past but would hate to lose valid work just because this went stale. Could you take a look and see whether this is something we should resolve conflicts on and revive, or go ahead and close?

**Comment by jonrohan** [comment]
I think we should close this for now, and reevaluate how we would implement this component.

**Pull request closed without merging**
