### PR TITLE
Move `Primer::Navigation::TabComponent` to `Primer::Alpha::Navigation::Tab`

### PR DESCRIPTION
**Pull request by mxriverlynn**
### Description

Move `Primer::Navigation::TabComponent` to `Primer::Alpha::Navigation::Tab`, and deprecate the original

### Integration

> Does this change require any updates to code in production?

not immediately, but deprecations need to be cleaned up

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews

### CODE REVIEW

**Comment by ollie-iterators** [comment]
bump

**Comment by lesliecdubs** [comment]
@jonrohan should we try to revive this PR, or would it best to close it and handle fresh? cc @hrs as this is related to the component renaming effort you've been getting up to speed on

**Comment by ollie-iterators** [comment]
It seems the only issue is that the<li> tag needs to be enclosed in an <ol> or <ul> tag, or the test needs to be disabled for this <li> element: <li data-view-component="true" class="d-inline-flex"><a data-view-component="true"><span data-view-component="true">Tab</span></a></li>

**Review by camertron — APPROVED** [review]
This looks good to me 👍

**Review by jonrohan — APPROVED** [review]
Looks good, feel free to merge this in :shipit:

**Pull request merged**
