### PR TITLE
fix accessibility violation by moving text to top of dialog on SelectPanel

### PR DESCRIPTION
**Pull request by owenniblock**
_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

The accessibility violation goes away if the content is presented at the top of the container element. Maybe it's not the best design wise so suggesting we make this change for now and then see if design want us to do some work to fix this in a different way.

### Screenshots

[Screenshots can be found here](https://github.com/primer/view_components/pull/3103/files?file-filters%5B%5D=.png&show-viewed-files=false)

### Integration

No

#### List the issues that this change affects.

Closes https://github.com/github/primer/issues/3958
Closes https://github.com/github/primer/issues/4019

#### Risk Assessment
  

- [x] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

Just a small layout tweak.

### What approach did you choose and why?

This is the simplest way to fix the accessibility violation.

### Accessibility

- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by keithamus — APPROVED** [review]
This LGTM but @langermank or @lukasoppermann should also check this over.

**Review by camertron — APPROVED** [review]
I'm ok with this too, but I wonder if a longer-term fix is to set a max height instead of a min.

**Review by langermank — APPROVED** [review]
It looks a little off balanced to me, but without digging into the CSS I don't really have an alternative. Maybe it would look a little better with a little bit more padding on the top? But I don't think its worth blocking this.

**Comment by camertron** [comment]
Yeah I agree with adding a bit more padding 👍

**Comment by camertron** [comment]
Looks like tests are failing under Rails main, I'll take a look.

**Pull request merged**
