### PR TITLE
rename kwargs to system_arguments

### PR DESCRIPTION
**Pull request by joelhawksley**
This PR renames the `kwargs` argument in the codebase to `system_arguments`, making the purpose of the argument clear.

### CODE REVIEW

**Review by BlakeWilliams — APPROVED** [review]
I like this a lot!

What are your thoughts on removing, or renaming the `_arguments` part of the name since it's now the "system_arguments argument". Maybe `system_options` or possibly `primer_options`? Not a blocker though 🙂

**Comment by joelhawksley** [comment]
> What are your thoughts on removing, or renaming the _arguments part of the name since it's now the "system_arguments argument".

I think there's room for improvement here for sure! For now, I wanted to match the naming exactly, so it's clear to readers of the docs that these arguments correspond to the System Arguments part of the documentation.

**Review by natashaU — COMMENTED** [review]
✅

**Comment by natashaU** [comment]
> > What are your thoughts on removing, or renaming the _arguments part of the name since it's now the "system_arguments argument".
> 
> I think there's room for improvement here for sure! For now, I wanted to match the naming exactly, so it's clear to readers of the docs that these arguments correspond to the System Arguments part of the documentation.

Agree here. I prefer system_arguments myself since this is the most clear to me.

**Pull request merged**
