### PR TITLE
add YARD & docs for CounterComponent

### PR DESCRIPTION
**Pull request by joelhawksley**
This PR introduces documentation for our components, written in [YARD](https://yardoc.org/). 

If we like this approach, I'd recommend that we look into a tool like [yardstick](https://github.com/dkubb/yardstick) to ensure our documentation is complete.

cc @manuelpuyol

### CODE REVIEW

**Comment by manuelpuyol** [comment]
hey @joelhawksley, just out of curiosity, why YARD and not RDoc?

**Comment by joelhawksley** [comment]
> hey @joelhawksley, just out of curiosity, why YARD and not RDoc?

@manuelpuyol YARD came recommended from `@jhawthorn`. Do you have a preference?

**Comment by manuelpuyol** [comment]
> > hey @joelhawksley, just out of curiosity, why YARD and not RDoc?
> 
> @manuelpuyol YARD came recommended from `@jhawthorn`. Do you have a preference?

nope, just curiosity haha

**Comment by manuelpuyol** [comment]
may we add how to deploy the docs/action to deploy it?

**Comment by joelhawksley** [comment]
@manuelpuyol my plan was to just use https://rubydoc.info/, which will auto-publish YARD docs from this repo 😄

**Review by manuelpuyol — APPROVED** [review]

**Pull request merged**
