### PR TITLE
Clear input when SelectPanel closed

### PR DESCRIPTION
**Pull request by owenniblock**
_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

Clearing the input when the SelectPanel dialog closes.

### Integration
No

#### List the issues that this change affects.

Relates to https://github.com/github/primer/issues/3932

#### Risk Assessment
  

- [x] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?

Easiest way to fix this was to clear the input in TypeScript when the `hide` method is called.

### Accessibility

- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.

### Merge checklist

- [x] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [x] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by camertron — CHANGES_REQUESTED** [review]
Hey @owenniblock, looking good!

I'm concerned that clearing out the filter input by doing `this.filterInputTextField.value = ''` won't trigger a remote request in remote fetch mode. Could you add a test for that case and ensure it works as expected?

Expected behavior:

1. On close, filter input text is cleared.
2. Panel closes and is hidden from view.
3. Since the filter text is now empty, the panel kicks off a remote fetch from the server and updates the list of items.
4. User re-opens the panel and sees the original list of items.

**Comment by owenniblock** [comment]
@camertron quick question on the exact functioning you're after here.

I can see that currently it doesn't do the fetch until the dialog is re-opened (it does do the fetch so it could be worse).

Do we want to trigger the fetch in the background when the dialog is hidden? I figure the positive to doing it this way is that the data is loaded ready when the user re-opens the dialog. Alternatively, if we leave it how it is, the positive is that if the user doesn't re-open the dialog (perhaps they opened it in error) we don't do an unnecessary call to re-populate the data.

Happy either way, just wanted to confirm before making a change from what's already there 😅

**Comment by camertron** [comment]
@owenniblock yeah, that's a great question. I personally think it's a bit jarring to see a list of items when you open the panel only to have those items more or less immediately replaced with another set of items. You'd be a second or so into visually scanning the items and then whoops! All replaced 🥴 

Thoughts?

**Comment by owenniblock** [comment]
@camertron yeah I think that makes sense. It's also a bit annoying that the loading is gone (there's a small loading spinner in the input itself). I'll see what I can do 😄

**Review by camertron — APPROVED** [review]
Cool 😎

**Pull request merged**
