### PR TITLE
Remove animations on actionlist checkmark

### PR DESCRIPTION
**Pull request by keithamus**
_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

Checkmarks are animated when they get selected/deselected, but also the way CSS animations work, the animation is also run whenever the element moves from `display:none` to a display where it is laid out.

This means whenever the menu is _opened_ all the checkboxes animate in, which looks... weird.

### Screenshots

https://github.com/primer/view_components/assets/118266/00d515a4-6cae-42be-8d48-0d7225490dea

#### List the issues that this change affects.

A user pointed this out on a public forum: https://ruby.social/@joeldrapper/111796664357341563

#### Risk Assessment
  

- [x] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?

I delete the animation

### Accessibility

- **Fixes axe scan violation** - This change fixes an existing [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation.
- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the violation cannot be resolved below.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by maximedegreve — APPROVED** [review]

**Comment by langermank** [comment]
@keithamus is there a way we can maintain the checkmark animation generally, but for this specific scenario (a menu opens that always has things checked) remove it? I'd love to pair with you on this before we completely remove it.

**Comment by keithamus** [comment]
I think the solution would be to add a class to the button or checkbox that is active once the checkbox is checked, and remains applied for the duration of the animation (or longer), and apply the animation to that class.

**Review by jonrohan — APPROVED** [review]
🤘🏻

**Review by langermank — APPROVED** [review]
I just wanna say I don't think its the animations fault 😆 I think its a nice animation. And something weird is happening with the menu. But agree snappy is good and you'll rarely see the animation since most menus close on selection.

So long old friend 👋

**Review by jonrohan — APPROVED** [review]

**Pull request merged**
