### PR TITLE
Build docs on Actions

### PR DESCRIPTION
**Pull request by srt32**
closes https://github.com/primer/view_components/issues/247

This change adds a workflow that will build the docs and statuses.json file on each push to `main`. It will then commit and push the changes directly to main.

This means that devs no longer have to build the docs (if they don't want to) since we'll automatically keep them up to date once a PR merges.

This change also removes the previously added CI check for the docs being stale.

### CODE REVIEW

**Comment by srt32** [comment]
@manuelpuyol I think this is ready but I am not sure how best to test it (given I'm working off my fork and can't push to this repo. I still don't know why...). Have any ideas?

**Comment by manuelpuyol** [comment]
@joelhawksley any idea why @srt32 can't push to the repo?

**Review by manuelpuyol — APPROVED** [review]

**Comment by joelhawksley** [comment]
> @joelhawksley any idea why @srt32 can't push to the repo?

I see @srt32 is an Admin when I look at the repository settings 🤔

**Comment by srt32** [comment]
I can do all the things in the UI but not from my CLI, which is very confusing. I'll keep trying things.

**Pull request merged**
