### PR TITLE
Update component status migrator to migrate from alpha or beta

### LINKED ISSUE #1263: component status migrator can't migrate out of alpha or beta subfolders
## problem

the `component_status_migrator.thor` script is unable to migrate any component status if the files exist in any folder other than the root `components/primer` folder. 

for example, `Primer::Alpha::ButtonMarketing` currently exists in the `components/primer/alpha` folder. if the migration script is run to try and move this folder it will fail because the files don't currently exist in the root folder.

## example: migrating ButtonMarketing from alpha to beta

running the migrator script on `ButtonMarketing` results in errors because the files are not in the currently expected root `components/primer` folder:

```shell
> bundle exec thor component_status_migrator ButtonMarketing --status beta

bundler: failed to load command: thor (/Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/bin/thor)
/Users/riverlynn/dev/github/view_components/component_status_migrator.thor:30:in `move_controller': unhandled exception
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/runner.rb:43:in `method_missing'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:29:in `run'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:135:in `run'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/bin/thor:6:in `<top (required)>'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/bin/thor:25:in `load'
	from /Users/riverlynn/dev/github/view_components/vendor/bundle/ruby/3.0.0/bin/thor:25:in `<top (required)>'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/cli.rb:479:in `exec'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/libexec/bundle:49:in `block in <top (required)>'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/riverlynn/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/libexec/bundle:37:in `<top (required)>'
	from /Users/riverlynn/.rbenv/versions/3.0.4/bin/bundle:23:in `load'
	from /Users/riverlynn/.rbenv/versions/3.0.4/bin/bundle:23:in `<main>'
```

## expected behavior

i can think of two possible options for correcting this:

1) the script should locate the existing files for the specified component, no matter what folder they are in

or

2) the script should correctly handle adding the current status vs the target status. maybe this looks like `thor component_status_migrator Alpha::ButtonMarketing --status beta` or `thor component_status_migrator ButtonMarketing --from-status alpha --to-status beta` or similar

### PR DESCRIPTION
**Pull request by hrs**
### Description
The status migrator currently only accepts components defined at the top level of the `app/components/primer`. Since we've moved most of those components into subdirectories, like `alpha/` and `beta/`, we'd like to be able to migrate those, too, so that we can automatically migrate components e.g. `alpha -> beta`.

This involves:

1. Determining the *current* status of the component. This can't just involve checking paths, but needs to involve inspecting the source code of the component for a `status` annotation, since when we migrate components we leave behind a file annotated with `status: :deprecated` representing the previous version of the component.
2. Manipulating the code by editing the module in which the component's defined. For example, `Primer::FooBar -> Primer::Alpha::FooBar` involves adding a `module Alpha` section, which we already do, but `Primer::Alpha::FooBar -> Primer::Beta::FooBar` requires recognizing and modifying that module.

This PR defines a `ComponentVersion` class representing a component and its status. We use that information to construct fully qualified class names and file paths. If a status isn't provided it infers the current version from a combination of file paths and source code.

While there still aren't automated tests for this script, you can try the manual commands to see how it works:

```sh
$ bundle exec thor component_status_migrator ButtonMarketing --status beta
Migrating Primer::Alpha::ButtonMarketing -> Primer::Beta::ButtonMarketing
      create  app/components/primer/beta/button_marketing.rb
      remove  app/components/primer/alpha/button_marketing.rb
      create  app/components/primer/beta/button_marketing.pcss
      remove  app/components/primer/alpha/button_marketing.pcss
        gsub  app/components/primer/primer.pcss
      create  test/components/beta/button_marketing_test.rb
      remove  test/components/alpha/button_marketing_test.rb
      create  previews/primer/beta/button_marketing_preview.rb
      remove  previews/primer/alpha/button_marketing_preview.rb
        gsub  app/components/primer/beta/button_marketing.rb
        gsub  app/components/primer/beta/button_marketing.rb
      insert  app/components/primer/beta/button_marketing.rb
      insert  app/components/primer/beta/button_marketing.rb
        gsub  previews/primer/beta/button_marketing_preview.rb
        gsub  previews/primer/beta/button_marketing_preview.rb
      insert  previews/primer/beta/button_marketing_preview.rb
      insert  previews/primer/beta/button_marketing_preview.rb
        gsub  previews/primer/beta/button_marketing_preview.rb
        gsub  previews/primer/beta/button_marketing_preview.rb
        gsub  test/components/beta/button_marketing_test.rb
        gsub  docs/src/@primer/gatsby-theme-doctocat/nav.yml
        gsub  docs/src/@primer/gatsby-theme-doctocat/nav.yml
        gsub  app/components/primer/primer.ts
         run  grep -rl ButtonMarketing . --exclude=.overmind.sock --exclude=CHANGELOG.md --exclude=test/components/alpha/button_marketing_test.rb --exclude-dir={.git,.cache,.yardoc,builds,log,node_modules,tmp,vendor} | xargs sed -i '' 's/Primer::Alpha::ButtonMarketing/Primer::Beta::ButtonMarketing/g' from "."
      remove  app/components/primer/alpha/button_marketing.rb
      create  app/components/primer/alpha/button_marketing.rb
      insert  lib/primer/deprecations.yml
      insert  test/components/component_test.rb
         run  bundle exec rubocop -a; exit 0 from "."

[...]

Component Status Migration Completed
------------------------------------

Original Component: 'Primer::Alpha::ButtonMarketing'
     New Component: 'Primer::Beta::ButtonMarketing'

IMPORTANT NOTE:

The original component has been migrated, but may need additional configuration. Please update the entry in 'lib/primer/deprecations.yml'.
```

Migrating a component in the `app/components/primer` directory still works, too:

```sh
$ bundle exec thor component_status_migrator Box --status beta
Migrating Primer::Box -> Primer::Beta::Box
      create  app/components/primer/beta/box.rb
      remove  app/components/primer/box.rb
        gsub  app/components/primer/primer.pcss
      create  test/components/beta/box_test.rb
      remove  test/components/box_test.rb
      insert  app/components/primer/beta/box.rb
      insert  app/components/primer/beta/box.rb
        gsub  test/components/beta/box_test.rb
        gsub  docs/src/@primer/gatsby-theme-doctocat/nav.yml
        gsub  docs/src/@primer/gatsby-theme-doctocat/nav.yml
        gsub  app/components/primer/primer.ts
         run  grep -rl Box . --exclude=.overmind.sock --exclude=CHANGELOG.md --exclude=test/components/box_test.rb --exclude-dir={.git,.cache,.yardoc,builds,log,node_modules,tmp,vendor} | xargs sed -i '' 's/Primer::Box/Primer::Beta::Box/g' from "."
      remove  app/components/primer/box.rb
      create  app/components/primer/box.rb
      insert  lib/primer/deprecations.yml
      insert  test/components/component_test.rb
         run  bundle exec rubocop -a; exit 0 from "."

[...]

Component Status Migration Completed
------------------------------------

Original Component: 'Primer::Box'
     New Component: 'Primer::Beta::Box'

IMPORTANT NOTE:

The original component has been migrated, but may need additional configuration. Please update the entry in 'lib/primer/deprecations.yml'.
```

### Questions/notes for the reviewer:

- Right now we always assume we want to migrate from the "latest" version of the component: if there's both an `alpha` and `beta` release, migrate from `beta`. That's fine for this ticket, I think, but it'll be an issue if we ever want to downgrade a component (say `beta -> alpha`). We might want a `--from-status` flag or something some day.
- I haven't used `thor` too much, and defining this big `ComponentVersion` class in the same file as the migration script seems clunky. Would there be a canonical directory for that class? I'm reluctant to just dump it in `lib`.
- I've followed the current practice of not writing tests for this script. But if `ComponentVersion` were extracted somewhere it might be nice to backfill some tests for it; that version inference code's a little hairy. Sound good?
- There's some logic in here for parsing and rewriting module names with regexes. I think the changes are still simple enough that we can get away with this, but we're coming right up the point where I'd want to manipulate an AST instead of a text file (I *think* RuboCop provides some tools to make this easier?). If you'd rather go that route, let me know!

Closes #1263.

### Integration

> Does this change require any updates to code in production?

Nope! This is just an internal tool.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews

### CODE REVIEW

**Comment by ollie-iterators** [comment]
Great job @hrs.

**Comment by jonrohan** [comment]
Tested this locally moving `Primer::Beta::Button` to `Primer::Button`, and got a few results that seem incorrect. Below is the output, it also moved `app/components/primer/beta/button_group.rb` I guess because it begins with `Button`? At the end it seemed to error out with `can't read s/Primer::Beta::Button/Primer::Button/g: No such file or directory`

```
@jonrohan ➜ /workspaces/view_components (hrs/component-status-migrator) $ bundle exec thor component_status_migrator Button --status stable
Migrating Primer::Beta::Button -> Primer::Button
      create  app/components/primer/button.rb
      remove  app/components/primer/beta/button.rb
      create  app/components/primer/button.html.erb
      remove  app/components/primer/beta/button.html.erb
      create  app/components/primer/button_group.rb
      remove  app/components/primer/beta/button_group.rb
      create  app/components/primer/button.pcss
      remove  app/components/primer/beta/button.pcss
      create  app/components/primer/button_group.html.erb
      remove  app/components/primer/beta/button_group.html.erb
        gsub  app/components/primer/primer.pcss
      create  previews/primer/button_preview.rb
      remove  previews/primer/beta/button_preview.rb
        gsub  app/components/primer/button.rb
        gsub  app/components/primer/button.rb
        gsub  previews/primer/button_preview.rb
        gsub  previews/primer/button_preview.rb
        gsub  previews/primer/button_preview.rb
        gsub  previews/primer/button_preview.rb
        gsub  docs/src/@primer/gatsby-theme-doctocat/nav.yml
        gsub  docs/src/@primer/gatsby-theme-doctocat/nav.yml
        gsub  app/components/primer/primer.ts
         run  grep -rl Button . --exclude=.overmind.sock --exclude=CHANGELOG.md --exclude=test/components/beta/button_test.rb --exclude-dir={.git,.cache,.yardoc,builds,log,node_modules,tmp,vendor} | xargs sed -i '' 's/Primer::Beta::Button/Primer::Button/g' from "."
sed: can't read s/Primer::Beta::Button/Primer::Button/g: No such file or directory
@jonrohan ➜ /workspaces/view_components (hrs/component-status-migrator) $ 
```

**Comment by hrs** [comment]
@jonrohan Thanks! I just pushed a commit to avoid accidentally renaming files prefixed with the name of the component being moved (so now we're moving `button.*` instead of `button*` in your example).

That second issue with `sed` is interesting! Any chance you're on a Linux machine? I can replicate that issue on my Mac if I modify the command to explicitly use GNU `sed`, but it works with BSD `sed`. Unfortunately, the options seem to be [mutually incompatible](https://stackoverflow.com/a/5694430).

[This is kind of gross](https://github.com/primer/view_components/pull/1899/commits/c088f2df5c61b506fe8374ef66a5f0a04c32d407) but it fixes the issue by checking if we're using GNU or FreeBSD `sed`. Similarly, [this handles differing word boundary syntax](https://github.com/primer/view_components/commit/ddb14f72bfca0f508a7defe620f64aa228b2b108).

**Comment by jonrohan** [comment]
> That second issue with `sed` is interesting! Any chance you're on a Linux machine? I can replicate that issue on my Mac if I modify the command to explicitly use GNU `sed`, but it works with BSD `sed`. Unfortunately, the options seem to be [mutually incompatible](https://stackoverflow.com/a/5694430).
> 
> [This is kind of gross](https://github.com/primer/view_components/pull/1899/commits/c088f2df5c61b506fe8374ef66a5f0a04c32d407) but it fixes the issue by checking if we're using GNU or FreeBSD `sed`. Similarly, [this handles differing word boundary syntax](https://github.com/primer/view_components/commit/ddb14f72bfca0f508a7defe620f64aa228b2b108).

ah yeah, I was using codespaces to test, that's probably the issue

**Comment by jonrohan** [comment]
Tested again, and moved all of button from beta to stable but one thing I noticed it missed was updating the `status: :beta` line in the button to stable https://github.com/primer/view_components/blob/bb627a21b0df7a109cbb939dbf8c171a368670bc/app/components/primer/beta/button.rb#L7

image

**Review by jonrohan — APPROVED** [review]
Works great! Thanks.

**Pull request merged**
