### PR TITLE
Update `Label` schemes to use functional names

### PR DESCRIPTION
**Pull request by manuelpuyol**
This PR:

1. Adds `accent`, `attention`, `severe`, `done` and `sponsors` schemes
2. Deprecates `info` and `warning`
3. Adds linter to migrate deprecated schemes

### CODE REVIEW

**Comment by jonrohan** [comment]
I think some of this was done in https://github.com/primer/view_components/pull/876?

**Comment by manuelpuyol** [comment]
> I think some of this was done in #876?

hah! didn't see that PR 😅 
could we close that in favor of this PR?

**Comment by simurai** [comment]
> could we close that in favor of this PR?

Yes, sure. Thanks for taking over. 🙇  I think I had to wait for an earlier release of PCSS to go first but was also got stuck getting CI to pass.

**Comment by manuelpuyol** [comment]
@jonrohan may I get some 👀 ?

**Pull request merged**
