### PR TITLE
Reduce allocations in `test/performance/bench_utilities.rb`

### PR DESCRIPTION
**Pull request by japf**
_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

This PR is reducing the allocations happening in the `lib/primer/classify/utilities.rb` file. During performance testing, we found that the `Primer::Classify::Utilities.supported_selector?` method was allocating more objects than expected. We have updated the method to use the `Regexp` object directly instead of creating a new `Regexp` object each time the method is called. 

### Screenshots
N/A

### Integration
N/A

#### List the issues that this change affects.
N/A

#### Risk Assessment
  

- [x] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### Accessibility

- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.

### Merge checklist

- [x] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by camertron** [comment]
Thanks for this @japf! I just merged main into your branch, which brings support for Ruby 3.3. You should be able to update the tests now.

**Comment by japf** [comment]
👋 @camertron,

I merged `main` again, edited the PR description and added the `skip-changeset` label. Please let me know if I'm missing anything.

**Comment by camertron** [comment]
Hey @japf, thanks for that! You'll also need to update the tests to reflect the new number of expected allocations.

**Comment by camertron** [comment]
Ok, it looks like the class name for the new test was `BenchClassify` which is the same name as another one of our perf test classes (probably a copypasta oversight). I think that was causing our tests to assert against the wrong number of allocations, depending on the order in which the test files were loaded. Hopefully this latest run works 👍

**Comment by camertron** [comment]
Huh, so weirdly if I run these new utility allocation tests multiple times, they report different numbers. We might need a warm-up or something before running them. Experimenting now.

**Review by camertron — APPROVED** [review]

**Pull request merged**
