### PR TITLE
Fix alphabetization of components in navigation of doc site

### PR DESCRIPTION
**Pull request by dwilsonactual**
Fix alphabetization of components in docs nav.
image
(IconButton should be a little higher up)

### CODE REVIEW

**Comment by camertron** [comment]
Thanks for this @dwilsonactual :) Could you add a CHANGELOG entry as well?

**Comment by dwilsonactual** [comment]
@camertron no problem. updated changelog, I think I did it right

**Review by camertron — APPROVED** [review]
LGTM 🎉

**Comment by dwilsonactual** [comment]
@camertron can you merge this it looks like I don't have permissions

**Comment by dwilsonactual** [comment]
@camertron sorry about that I think it should be good to go now

**Pull request merged**
