### PR TITLE
Update label.md

### PR DESCRIPTION
**Pull request by maxbeizer**
This removes some extra spacing in the initalizer that was making me a little eye twitchy

### CODE REVIEW

**Comment by manuelpuyol** [comment]
hey @maxbeizer! would you mind updating the comment in https://github.com/primer/view_components/blob/bd00fef3eb912273e7c4a9537519179a0ed38809/app/components/primer/label_component.rb#L34-L50?
the file you updated is generated based in the above

**Comment by maxbeizer** [comment]
updated @manuelpuyol . Thanks!

**Comment by maxbeizer** [comment]
Happy to squash if you'd like

**Comment by manuelpuyol** [comment]
> Happy to squash if you'd like

we squash on merge, so no worries!

**Review by manuelpuyol — APPROVED** [review]

**Pull request merged**
