### PR TITLE
rename Primer::BaseButton to Primer::Beta::BaseButton

### PR DESCRIPTION
**Pull request by mxriverlynn**
split from #676 - Standardize component naming

## summary

this PR uses `bundle exec thor component_status_migrator BaseButton --status=beta` to move the `BaseButton` to `Beta::BaseButton`, correcting all of the associated references, tests, stories, docs, etc.

## other changes

* ensure all references to `BaseButton` are now through `Primer::Beta::BaseButton`
* test to ensure `Primer::BaseButton` is a valid reference / alias to `Primer::Beta::BaseButton`

## file changes to note

the majority of the files changed in this PR are references to `Primer::BaseButton` being renamed to `Primer::Beta::BaseButton`.  with that said, these are the files that should be the focus of code review:

* `app/components/primer/base_button.rb` - DELETED (moved)
* `app/components/primer/beta/base_button.rb` - NEW (move)
* `lib/rubocop/cop/primer/component_name_migration.rb` - UPDATED deprecation list
* `static/arguments.yml` - UPDATED to reflect new file location, etc.
* `stories/primer/base_button_stories.rb` - DELETED (moved)
* `stories/primer/beta/base_button_stories.rb` - NEW (move)
* `test/components/base_button_test.rb` - DELETED (moved)
* `test/components/beta/base_button_test.rb` - NEW (move) and UPDATED to test `Primer::BaseButton` alias

## questions

* should `BaseButton` be included in the docs `nav.yml`? there's [a page for it](https://primer.style/view-components/components/basebutton), but no reference in the sidebar nav

### CODE REVIEW

**Comment by mxriverlynn** [comment]
for my own understanding: why do my PRs keep failing the `deploy` check?

```shell
Run paper-spa/deploy-pages@main
{}
Error: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

**Review by camertron — APPROVED** [review]
Nice! 🎉

**Comment by camertron** [comment]
@mxriverlynn hmm I'm not sure why that environment variable wouldn't be available, but my hunch is it's permission-related. Let me see if I can sort it out.

**Comment by camertron** [comment]
Ok @mxriverlynn I've added you as a maintainer which I'm hoping will sort out the access issues. Can you accept the invite? It should have been sent to your email.

**Comment by mxriverlynn** [comment]
@camertron still failing. thanks, tho! we'll figure it out eventually

**Comment by camertron** [comment]
Weird! Any ideas @rezrah?

**Comment by camertron** [comment]
@mxriverlynn looks like this happened because the PR was submitted from a fork. In the future, go ahead and submit PRs directly to the primer/view_components repo 😄

**Pull request merged**
